### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by jlennox** [G-Rath/strongly-typed-event-emitter#5]
```typescript
enum FooEvent {
  Blah = 'blah',
}

interface FooEventMap extends Record<string, unknown> {
  [FooEvent.Blah]: { ev: number };
}

class Foo extends StronglyTypedEventEmitter<FooEventMap> {
}

const foo = new Foo();
foo.on('blah', () => {}); // Does not produce a compiler error
foo.on(FooEvent.Blah, () => {}); // Does not produce a compiler error
```

The `extends Record<string, unknown>` is needed otherwise I get:
> Type 'FooEventMap' does not satisfy the constraint 'Record<string | number | symbol, unknown>'.
>  Index signature is missing in type 'FooEventMap'.ts(2344)

I'm using typescript Version 4.1.3. I'm wondering if it no longer works with this version?

**Comment by G-Rath** [comment]
That's quite possible - it's actually been a while since I've used event emitters and needed this library 😓 

I'll have a look into this if I get a chance, and see if it can be improved.

**Comment by PerfectionVR** [comment]
![image](https://user-images.githubusercontent.com/16305895/223476708-47a39f64-ab96-40d6-bb24-0fb734848122.png)
In a fresh nextjs typescript app unfortunately this is the case.

**Comment by G-Rath** [comment]
You should be able to mostly fix it by having your interface extend `EventMap` - see [this playground](https://www.typescriptlang.org/play?&q=264#code/JYWwDg9gTgLgBAbzgQzMANHARjAdgZzgF84AzKCEOAcmQHcBTfShgWlTGoG4AoUSWIjgBRAG4NcMYSGAwYDKMTIUq1BuMn5ufcNHhIAyjAq4A5gBsAngBVLYBgBMxEqTLkLMzyQFlUS8pQ0+MYQZlasMHaOrOouMW7yUNp8kgqkyADGDHAAqvgKXjD4vmBwDAAe8rgOhIUliDxwNAwAXACu+VAAdOYQpsC41C1CMBAA1hLDwVADpsS8TWrtnT19EG0wQ0IdCsNIpMBQwQByyCCtcNOzSkS8RDw8APSPcLgQ8nAwABbAhBnIuBQ5mY2GyDlC2WQhAARBlQsEytkALyvBh0OBGEwWGxRJwaVyyRIAHjyBXxxVQAD4ABQASi40J4cII8AYF0xoWxtnseJc0kJChJnUKFLAlLgKNwaJE+P57igdN4PDZXVC1KWO26vX6g0wDmQMGQEvFCEacGecGsBgATABWW0ARmGAAUKPZYJYaKMxlLqHBwUxXu8yuVfvBQp8ojQkN7JpdjLMuMRqF04AARYAOOCWdZwc4Ar3jCTUAD8ZuZCNjgJR+sNXW9UqVTVQwC6+RgAEENl9rEXcNSq-SeEQh08XlbrQBmAAstuGHagpja50kcAgpEj9ho0NamrbwFMbw20L9vyD8Ch+APuGQWHM2VGcDAyCgZwYiTXG8iW+oO+WClWHVoTgAAfOA-z3bV1hgE8umVBhVX7DUVivQ9oOoPUDSNJETXLeEIHvQDqVrZAuj3A4jhgU5zkwagvihS5r0cNcNmoIcRyVFU1WQgCoNYzDDWNBomgrAiEO1YisLIlYKJON9aPowhUKlLN0PY0ccAIQDoMQjJzGADIxglOA6SE00mgtCcZznOAFyXFdwy-KNqAQIhT0IN4L3wZTb3vT4ICfF83w-ddN2yFy4E1PYyEOOTzimBMzCTW5kzgpoVQYNx1V3FY+M2TBXPYrggA).

It looks like though that won't cause an unknown event name to trigger an error, but I'm actually not sure if that is possible now while still being able to extend `EventEmitter` in the types.

**Comment by jlennox** [comment]
I don't want to have a long standing issue opened.
